import { ContentInfo } from "../types";
import webdev_v2 from '../assets/images/png/services/webdev-v2.png'
import ai_v2 from '../assets/images/png/services/ai-v2.png'
import backdev_v2 from '../assets/images/png/services/backdev-v2.png'
import bulb_v2 from '../assets/images/png/services/bulb-v2.png'
import performance_v2 from '../assets/images/png/services/performance-v2.png'
import mobile_v2 from '../assets/images/png/services/mobile-v2.png'
import design_v2 from '../assets/images/png/services/design-v2.png'
import devops_v2 from '../assets/images/png/services/devops-v2.png'
import seo_v2 from '../assets/images/png/services/seo-v2.png'
import graphics_v2 from '../assets/images/png/services/graphics-v2.png'

// Initial manual services
export const serviceContent: ContentInfo[] = [
    {
        title: 'Web Development',
        content: 'Custom web applications with modern technologies and scalable architecture',
        icon: 'webdev',
        points: [
            'React, Next.js & Remix',
            'TypeScript, JavaScript & Python',
            'Performance Optimization'
        ],
        id: 0,
        url: 'web-development'
    },
    {
        title: 'Mobile Apps',
        content: 'Native and cross-platform mobile solutions for iOS and Android',
        icon: 'mobile',
        points: [
            'React Native',
            'Flutter',
            'Native Development'
        ],
        id: 1,
        url: 'mobile-apps'
    },
    {
        title: 'UI/UX Design',
        content: 'Beautiful and intuitive user experiences that drive engagement',
        icon: 'design',
        points: [
            'User Research',
            'Prototyping',
            'Design Systems'
        ],
        id: 2,
        url: 'ui-ux-design'
    },
    {
        title: 'Backend Solutions',
        content: 'Robust server architecture and API development for scalable systems',
        icon: 'backdev',
        points: [
            'Cloud Infrastructure',
            'Database Design',
            'API Development'
        ],
        id: 3,
        url: 'backend-solutions'
    },
    {
        title: 'DevOps & Automation',
        content: 'Streamline development and deployment pipelines with CI/CD and infrastructure automation',
        icon: 'devops',
        points: [
            'CI/CD Pipelines',
            'Infrastructure as Code',
            'Containerization & Orchestration'
        ],
        id: 4,
        url: 'devops-automation'
    },
    {
        title: 'Graphic Design & Branding',
        content: 'Create strong brand identities and visual assets that leave an impact',
        icon: 'graphics',
        points: [
            'Logo & Brand Identity',
            'Marketing Collateral',
            'Illustration & Animation'
        ],
        id: 8,
        url: 'graphic-design-branding'
    },
    {
        title: 'Performance',
        content: 'Lightning-fast and optimized solutions for maximum efficiency',
        icon: 'performance',
        points: [
            'Speed Optimization',
            'SEO',
            'Analytics'
        ],
        id: 5,
        url: 'performance'
    },
    {
        title: 'IT Solutions & Support',
        content: 'Reliable IT services and support to keep your business running smoothly',
        icon: 'bulb',
        points: [
            'System Maintenance',
            'Remote Support',
            'Security & Monitoring'
        ],
        id: 6,
        url: 'it-solutions-support'
    },
    {
        title: 'SEO & Digital Marketing',
        content: 'Drive traffic and conversions with tailored SEO and marketing strategies',
        icon: 'seo',
        points: [
            'Search Engine Optimization',
            'Content Marketing',
            'Social Media Strategy'
        ],
        id: 7,
        url: 'seo-digital-marketing'
    },
    {
        title: 'AI & Automation',
        content: 'Empower your systems with AI-powered tools and workflow automation',
        icon: 'ai',
        points: [
            'Chatbots & NLP',
            'Process Automation',
            'Custom AI Solutions'
        ],
        id: 9,
        url: 'ai-automation'
    }
];

export const detailedPageData = [
    {
        flip: {
            icon: webdev_v2,
            content: 'Building Digital Dreams into Reality'
        },
        head: [
            'Web Development',
            'Transform your vision into stunning, high-performance web applications that engage users and drive business growth.'
        ],
        offer: [
            'modernframework',
            'code',
            'Modern Framework',
            'React, Next.js, and TypeScript for robust applications',
            ';',
            'performanceoptimized',
            'light',
            'Performance Optimized',
            'Lightning-fast loading with SEO-friendly architecture',
            ';',
            'responsivedesign',
            'responsive',
            'Responsive Design',
            'Perfect experience across all devices and screen sizes',
            ';',
            'securityfirst',
            'shield',
            'Security First',
            'Built with security best practices and data protection',
            ';',
            'scalablebackend',
            'stack',
            'Scalable Backend',
            'Robust database solutions that grow with your business',
            ';',
            'easymaintenance',
            'setting',
            'Easy Maintenance',
            'Clean code structure for easy updates and modifications'
        ],
        choose: [
            'goal',
            'Goal-Oriented Development',
            'Every line of code serves your business objectives. We focus on creating solutions that drive real results and meet your specific requirements.',
            ';',
            'rocket',
            'Lightning Fast Performance',
            'Optimized for speed and performance with modern technologies. Your users will enjoy seamless experiences that keep them engaged.',
            ';',
            'users',
            'User-Centric Design',
            'Designed with your audience in mind. We create intuitive interfaces that users love and that convert visitors into customers.'
        ],
        process: [
            'bulb',
            'Discovery & Planning',
            'We dive deep into understanding your vision, business goals, and target audience to create a comprehensive project roadmap.',
            'Requirements gathering, competitor analysis, technology stack selection, and project timeline creation.',
            ';',
            'pencil',
            'Design & Wireframing',
            'Creating user-friendly wireframes and visual concepts that align with your brand and user expectations.',
            'User experience design, visual mockups, responsive layouts, and interactive prototypes.',
            ';',
            'code',
            'Development & Coding',
            'Building your application with modern technologies, clean code practices, and scalable architecture.',
            'Frontend development, backend integration, database setup, and API development.',
            ';',
            'shield',
            'Testing & Quality Assurance',
            'Rigorous testing across devices, browsers, and scenarios to ensure flawless functionality.',
            'Unit testing, integration testing, performance testing, and security audits.',
            ';',
            'rocket',
            'Launch & Support',
            'Smooth deployment with ongoing support to ensure your application runs perfectly in production.',
            'Domain setup, hosting configuration, monitoring setup, and maintenance support.'
        ],
        technologies: [
            
        ]
    },
    {
        flip: {
            icon: mobile_v2,
            content: 'Turning Ideas into Mobile Experiences'
        },
        head: [
            'Mobile App Development',
            'Crafting seamless native and cross-platform apps that captivate users and deliver performance on iOS and Android.'
        ],
        offer: [
            'crossplatform',
            'mobile',
            'Cross-Platform Efficiency',
            'Develop once, deploy everywhere with React Native and Flutter',
            ';',
            'nativeperformance',
            'speed',
            'Native Performance',
            'Harness the power of Swift, Kotlin, and platform-specific features',
            ';',
            'uiuxfirst',
            'design',
            'UI/UX First',
            'Delightful interfaces designed with users in mind',
            ';',
            'secureapps',
            'shield',
            'Secure Apps',
            'Built with encryption, secure storage, and authentication best practices',
            ';',
            'scalableapps',
            'stack',
            'Scalable Architecture',
            'Engineered to scale as your user base grows',
            ';',
            'storelaunch',
            'rocket',
            'App Store Ready',
            'Full support for Apple App Store and Google Play launches'
        ],
        choose: [
            'innovation',
            'Innovative Features',
            'Implement modern capabilities like geolocation, push notifications, and offline access to enhance user experience.',
            ';',
            'customux',
            'Custom Experiences',
            'Tailored interactions that feel native and intuitive to your audience.',
            ';',
            'agileprocess',
            'Agile Development',
            'Iterative approach for faster releases and ongoing improvements.'
        ],
        process: [
            'bulb',
            'Idea to Concept',
            'We analyze your app idea, identify goals, and define core features.',
            'Requirement mapping, user flow planning, and feature prioritization.',
            ';',
            'pencil',
            'Design & Prototyping',
            'Crafting interactive mockups that reflect your brand and user needs.',
            'Wireframes, UI/UX, user feedback loop.',
            ';',
            'code',
            'App Development',
            'Building the application for iOS and Android with optimized code.',
            'React Native, Flutter, Native SDKs, backend APIs.',
            ';',
            'shield',
            'Testing & QA',
            'Extensive device and performance testing before go-live.',
            'Unit tests, device compatibility, bug fixing.',
            ';',
            'rocket',
            'Deployment & Support',
            'Launching your app and providing maintenance & analytics support.',
            'Play Store, App Store, crash monitoring, updates.'
        ]
    },
    {
        flip: {
            icon: design_v2,
            content: 'Designs That Speak and Perform'
        },
        head: [
            'UI/UX Design',
            'Creating delightful, accessible, and strategic interfaces that enhance usability and drive engagement.'
        ],
        offer: [
            'userresearch',
            'search',
            'User Research',
            'Deep understanding of your audience’s behavior and needs',
            ';',
            'wireframes',
            'pencil',
            'Wireframes & Prototypes',
            'Visual planning and interactive demos before development',
            ';',
            'visualdesign',
            'palette',
            'Visual Design',
            'Pixel-perfect, brand-aligned interface elements',
            ';',
            'designsystems',
            'layout',
            'Design Systems',
            'Reusable, scalable, and maintainable component libraries',
            ';',
            'a11y',
            'accessibility',
            'Accessibility & Usability',
            'Inclusive design for all users regardless of ability',
            ';',
            'collabdev',
            'code',
            'Developer Collaboration',
            'Designs built to be implemented seamlessly by developers'
        ],
        choose: [
            'humanfirst',
            'Human-Centered Design',
            'Focus on intuitive interactions that anticipate user needs and behaviors.',
            ';',
            'brandmatch',
            'Brand Consistency',
            'Visually aligned with your identity, vision, and tone of voice.',
            ';',
            'iterative',
            'Refined Iteration',
            'Incorporating feedback loops to ensure optimal user satisfaction.'
        ],
        process: [
            'bulb',
            'Research & Discovery',
            'Understanding user personas, journey maps, and expectations.',
            'Stakeholder interviews, user flows, competitor audit.',
            ';',
            'pencil',
            'Sketching & Wireframes',
            'Designing structure and interaction of pages and flows.',
            'UX wireframes, low-fidelity mockups.',
            ';',
            'palette',
            'Visual Design',
            'Applying styles, typography, and brand colors.',
            'UI kits, high-fidelity mockups, iconography.',
            ';',
            'code',
            'Handoff & Support',
            'Preparing dev-ready assets and assisting during build phase.',
            'Zeplin/Figma exports, style guides, QA collaboration.',
            ';',
            'shield',
            'Usability Testing',
            'Testing with real users for practical validation.',
            'A/B testing, surveys, interaction analytics.'
        ]
    },
    {
        flip: {
            icon: backdev_v2,
            content: 'Powering Your Products Behind the Scenes'
        },
        head: [
            'Backend Solutions',
            'Delivering secure, scalable, and high-performance server-side architecture that fuels your business applications.'
        ],
        offer: [
            'apiintegration',
            'code',
            'API Development',
            'RESTful and GraphQL APIs designed for performance and flexibility',
            ';',
            'securearch',
            'shield',
            'Secure Architecture',
            'Security best practices built into every layer',
            ';',
            'dbdesign',
            'stack',
            'Database Design',
            'Efficient data models using SQL and NoSQL technologies',
            ';',
            'auth',
            'lock',
            'Authentication & Authorization',
            'JWT, OAuth, and RBAC for access control and user security',
            ';',
            'realtime',
            'wifi',
            'Real-Time Data',
            'Socket.IO and WebSockets for instant data sync and interaction',
            ';',
            'cloudinfra',
            'cloud',
            'Cloud Infrastructure',
            'Deploy on AWS, GCP, or Azure with full monitoring and scaling'
        ],
        choose: [
            'scalability',
            'Scalable from Day One',
            'Designed to grow with your traffic and feature complexity.',
            ';',
            'modularcode',
            'gear',
            'Modular & Maintainable',
            'Clean structure that’s easy to expand, refactor, and debug.',
            ';',
            'reliableapi',
            'plug',
            'Reliable APIs',
            'Your frontend always gets exactly the data it needs—nothing more, nothing less.'
        ],
        process: [
            'bulb',
            'Planning & Blueprint',
            'Understanding data flow, security needs, and integration points.',
            'Entity modeling, API contracts, and stack selection.',
            ';',
            'pencil',
            'Schema & Architecture',
            'Designing scalable and robust backend systems.',
            'Database schema, microservices, auth flow, cloud diagram.',
            ';',
            'code',
            'Development',
            'API and service development using best practices.',
            'REST/GraphQL APIs, database seeding, cloud storage.',
            ';',
            'shield',
            'Testing & Validation',
            'Securing, stress-testing, and monitoring service reliability.',
            'Load testing, failover checks, test suites.',
            ';',
            'rocket',
            'Deployment & Maintenance',
            'Launching with CI/CD pipelines and monitoring tools.',
            'Monitoring alerts, logs, scaling policies, support.'
        ]
    },
    {
        flip: {
            icon: devops_v2,
            content: 'Deploy Faster. Operate Smarter.'
        },
        head: [
            'DevOps & Automation',
            'Automating your development workflows and infrastructure for speed, reliability, and scale.'
        ],
        offer: [
            'cicd',
            'sync',
            'CI/CD Pipelines',
            'Automated build, test, and deployment pipelines',
            ';',
            'infraascode',
            'terminal',
            'Infrastructure as Code',
            'Manage servers and networks through code with Terraform & Ansible',
            ';',
            'containerization',
            'box',
            'Containerization',
            'Dockerized environments for consistent deployment across platforms',
            ';',
            'orchestration',
            'grid',
            'Kubernetes Orchestration',
            'Automated scaling, self-healing, and deployment rollbacks',
            ';',
            'monitoring',
            'eye',
            'Monitoring & Logging',
            'Real-time tracking with tools like Prometheus, Grafana, and ELK Stack',
            ';',
            'versioncontrol',
            'git',
            'Version Control & Automation',
            'Best practices using Git, branching, and automation workflows'
        ],
        choose: [
            'reduceddowntime',
            'clock',
            'Zero-Downtime Deployments',
            'Safely release updates with blue-green or rolling strategies.',
            ';',
            'teamproductivity',
            'users',
            'Developer Productivity',
            'Faster feedback loops and safer shipping with automation.',
            ';',
            'costefficiency',
            'dollar-sign',
            'Cost Efficiency',
            'Automated scaling and infrastructure rightsizing to save costs.'
        ],
        process: [
            'bulb',
            'Assessment & Goals',
            'Understanding your dev flow, environments, and pain points.',
            'Toolchain evaluation, infra audit, roadmap planning.',
            ';',
            'code',
            'CI/CD Setup',
            'Integrating automated pipelines for every deployment step.',
            'GitHub Actions, GitLab CI, Bitbucket Pipelines.',
            ';',
            'box',
            'Containerization & Infra',
            'Building container-based infrastructure for rapid scaling.',
            'Dockerfiles, Kubernetes YAMLs, Helm charts.',
            ';',
            'eye',
            'Monitoring & Alerts',
            'Ensuring transparency and quick response to failures.',
            'Cloudwatch, ELK Stack, custom alerting scripts.',
            ';',
            'rocket',
            'Ongoing Optimization',
            'Refining performance, improving pipelines, and auditing usage.',
            'Audit logs, dependency upgrades, scaling strategies.'
        ]
    },
    {
        flip: {
            icon: graphics_v2,
            content: 'Crafting Brands That Resonate'
        },
        head: [
            'Graphic Design & Branding',
            'Building visual identities that connect emotionally and represent your brand’s core values.'
        ],
        offer: [
            'brandidentity',
            'palette',
            'Brand Identity',
            'Logos, typography, and color systems with lasting impressions',
            ';',
            'marketingcollateral',
            'file',
            'Marketing Collateral',
            'Professional assets for print and digital marketing',
            ';',
            'socialmedia',
            'camera',
            'Social Media Design',
            'Eye-catching creatives for social engagement',
            ';',
            'illustration',
            'brush',
            'Custom Illustration',
            'Tailor-made artwork that enhances storytelling',
            ';',
            'motiongraphics',
            'film',
            'Motion Graphics',
            'Animated content to make your brand pop',
            ';',
            'styleguides',
            'book',
            'Style Guides',
            'Consistent rules for applying brand across channels'
        ],
        choose: [
            'emotion',
            'Emotionally Driven',
            'Designs that evoke trust, excitement, and brand recall.',
            ';',
            'consistency',
            'Brand Consistency',
            'Maintain design uniformity across every platform.',
            ';',
            'differentiation',
            'star',
            'Stand Out from the Crowd',
            'Create a unique identity that sets you apart from competitors.'
        ],
        process: [
            'bulb',
            'Discovery & Moodboarding',
            'Exploring your brand’s values, voice, and visual goals.',
            'Brand questionnaire, moodboards, competitor scan.',
            ';',
            'pencil',
            'Conceptualization',
            'Drafting multiple design routes and refining the visual direction.',
            'Logo sketches, typography combos, sample posters.',
            ';',
            'palette',
            'Asset Creation',
            'Designing final creatives and packaging files for use.',
            'Logo variations, social banners, PDF/print formats.',
            ';',
            'film',
            'Animation (Optional)',
            'Animating logos or explainer content for dynamic branding.',
            'GIFs, Lottie, AE exports.',
            ';',
            'book',
            'Style Guide Delivery',
            'Complete guide to ensure consistency across all teams.',
            'Fonts, color codes, logo usage rules, templates.'
        ]
    },
    {
        flip: {
            icon: performance_v2,
            content: 'Speed, Stability, and Scalability'
        },
        head: [
            'Performance Optimization',
            'Enhancing every millisecond to deliver blazing-fast user experiences that scale with demand.'
        ],
        offer: [
            'speedboost',
            'zap',
            'Speed Boosting',
            'Reduce load time and increase responsiveness across your platform',
            ';',
            'seo',
            'search',
            'SEO Optimization',
            'Optimize structure and metadata for better search rankings',
            ';',
            'lazyload',
            'image',
            'Lazy Loading & Caching',
            'Efficient media loading and caching strategies for smooth delivery',
            ';',
            'cdn',
            'globe',
            'CDN Integration',
            'Distribute content worldwide using Cloudflare, AWS, and others',
            ';',
            'audits',
            'bar-chart',
            'Performance Audits',
            'Identify and fix bottlenecks with tools like Lighthouse & Web Vitals',
            ';',
            'metrics',
            'pie-chart',
            'Real-Time Metrics',
            'Track page speed, TTFB, and more with integrated analytics'
        ],
        choose: [
            'firstimpression',
            'Great First Impressions',
            'Speed influences perception—ensure users stay and convert.',
            ';',
            'rankingedge',
            'trophy',
            'SEO + Speed Synergy',
            'Faster sites rank higher on Google—every second counts.',
            ';',
            'globalaccess',
            'map',
            'Optimized for Global Reach',
            'Quick delivery across geographies with CDN and regional caching.'
        ],
        process: [
            'bulb',
            'Performance Evaluation',
            'Assess site and app bottlenecks via audits and monitoring.',
            'Lighthouse scores, Core Web Vitals, server timing reports.',
            ';',
            'code',
            'Optimization Strategies',
            'Apply code-splitting, lazy loading, and compression techniques.',
            'Tree-shaking, gzip/brotli, responsive image delivery.',
            ';',
            'cloud',
            'CDN & Cache Setup',
            'Implement CDN, browser caching, and asset versioning.',
            'Cloudflare, S3, Redis/MemoryStore setup.',
            ';',
            'monitor',
            'Real-Time Monitoring',
            'Use dashboards to observe load times and runtime behavior.',
            'Datadog, New Relic, GA4 custom metrics.',
            ';',
            'repeat',
            'Continuous Tuning',
            'Iterative improvements based on data and seasonal load changes.',
            'Performance regression checks, A/B test rollouts.'
        ]
    },
    {
        flip: {
            icon: bulb_v2,
            content: 'Keeping Your Tech Running Smoothly'
        },
        head: [
            'IT Solutions & Support',
            'Reliable IT infrastructure, troubleshooting, and proactive support to keep your business running without interruption.'
        ],
        offer: [
            'systemmaintenance',
            'settings',
            'System Maintenance',
            'Regular updates, patching, and performance checks',
            ';',
            'remotesupport',
            'phone',
            'Remote Support',
            'Quick fixes and diagnostics without on-site visits',
            ';',
            'securitymonitor',
            'shield',
            'Security Monitoring',
            'Real-time alerts, firewall configs, and threat detection',
            ';',
            'networkinfra',
            'wifi',
            'Network Infrastructure',
            'Setup and monitoring of LAN, WAN, and VPN',
            ';',
            'backupsolutions',
            'cloud-upload',
            'Backup Solutions',
            'Scheduled data backups and recovery systems',
            ';',
            'emailconfig',
            'mail',
            'Email & Server Setup',
            'Professional business emails, SMTP, and custom domains'
        ],
        choose: [
            'nobreaks',
            'Business Continuity',
            'We ensure minimal downtime and immediate problem resolution.',
            ';',
            'costeffective',
            'dollar-sign',
            'Cost-Effective Support',
            'Get enterprise-grade IT service without the in-house cost.',
            ';',
            'secureinfra',
            'lock',
            'Secure & Scalable Infrastructure',
            'Safeguard systems and scale operations with confidence.'
        ],
        process: [
            'bulb',
            'Assessment & Setup',
            'Understanding your current systems and potential failure points.',
            'Hardware/software audit, risk evaluation, setup planning.',
            ';',
            'shield',
            'Security & Policy',
            'Implement secure access control and usage policies.',
            'Firewall, antivirus, MFA setup, access governance.',
            ';',
            'phone',
            'Support Enablement',
            'Set up remote assistance tools and escalation protocols.',
            'TeamViewer, AnyDesk, ticketing system integration.',
            ';',
            'cloud-upload',
            'Backup & Recovery',
            'Establish redundant backups and fast restore pipelines.',
            'On-premise + cloud hybrid solutions.',
            ';',
            'monitor',
            'Continuous Monitoring',
            'Track device health, software versions, and vulnerabilities.',
            'Daily reports, alert systems, remote interventions.'
        ]
    },
    {
        flip: {
            icon: seo_v2,
            content: 'Visibility That Converts'
        },
        head: [
            'SEO & Digital Marketing',
            'Boost visibility, attract the right audience, and convert traffic into loyal customers with expert SEO and digital campaigns.'
        ],
        offer: [
            'onpageseo',
            'edit',
            'On-Page SEO',
            'Content structure, keywords, metadata, and internal linking',
            ';',
            'offpageseo',
            'link',
            'Off-Page SEO',
            'Backlinks, guest posts, and reputation building',
            ';',
            'contentstrategy',
            'book-open',
            'Content Marketing',
            'Drive traffic with blogs, whitepapers, and infographics',
            ';',
            'smm',
            'message-circle',
            'Social Media Marketing',
            'Engage and grow your audience across platforms',
            ';',
            'paidads',
            'dollar-sign',
            'PPC & Paid Ads',
            'Targeted ad campaigns via Google, Meta, and more',
            ';',
            'analytics',
            'bar-chart-2',
            'Analytics & Reports',
            'Data-driven strategies from Google Analytics, SEMrush, etc.'
        ],
        choose: [
            'relevancetraffic',
            'target',
            'Attract the Right Traffic',
            'We don’t chase clicks—we deliver value and conversions.',
            ';',
            'longtermvalue',
            'clock',
            'Long-Term Growth',
            'Organic SEO builds trust and ROI over time.',
            ';',
            'strategybacked',
            'compass',
            'Strategy-Backed Execution',
            'Every campaign is driven by research, not guesswork.'
        ],
        process: [
            'bulb',
            'Audit & Competitor Analysis',
            'Review current SEO health and compare against industry leaders.',
            'Keyword gap, backlink profile, UX audit.',
            ';',
            'edit',
            'On-Page Optimization',
            'Revamp pages for SEO best practices.',
            'Alt tags, titles, headers, canonical tags.',
            ';',
            'link',
            'Off-Page & Outreach',
            'Build authority through link-building and PR.',
            'Directories, influencer collabs, brand mentions.',
            ';',
            'message-circle',
            'Campaigns & SMM',
            'Run targeted social and ad campaigns.',
            'Paid promotions, post calendar, creatives.',
            ';',
            'bar-chart-2',
            'Reporting & Strategy',
            'Track KPIs and refine approaches monthly.',
            'Ranking report, heatmaps, ad ROI, conversion rate.'
        ]
    },
    {
        flip: {
            icon: ai_v2,
            content: 'Smarter Systems for a Smarter Future'
        },
        head: [
            'AI & Automation',
            'Leverage artificial intelligence and intelligent automation to simplify operations and unlock new potential.'
        ],
        offer: [
            'chatbots',
            'message-square',
            'AI Chatbots',
            'Automate customer interaction using NLP and ML models',
            ';',
            'processautomation',
            'repeat',
            'Process Automation',
            'Automate repetitive workflows to reduce human error and cost',
            ';',
            'predictiveanalytics',
            'activity',
            'Predictive Analytics',
            'Forecast trends and outcomes using historical data',
            ';',
            'customai',
            'cpu',
            'Custom AI Solutions',
            'Tailored ML models and AI integrations for your use case',
            ';',
            'visionai',
            'eye',
            'Computer Vision',
            'Image recognition, detection, and OCR for automation',
            ';',
            'dataenrichment',
            'database',
            'Data Enrichment',
            'Smart tagging, cleansing, and structuring of raw datasets'
        ],
        choose: [
            'timecostsaving',
            'clock',
            'Save Time & Resources',
            'Automate routine tasks so your team focuses on what matters.',
            ';',
            'competitiveedge',
            'trending-up',
            'Gain a Competitive Edge',
            'Use insights and automation to outpace competition.',
            ';',
            'tailoredai',
            'sliders',
            'Tailored to Your Needs',
            'No one-size-fits-all—we build custom tools just for you.'
        ],
        process: [
            'bulb',
            'Use Case Discovery',
            'Identify repetitive processes and opportunities for AI impact.',
            'Workflow analysis, KPI mapping.',
            ';',
            'cpu',
            'Model Selection or Training',
            'Choose or train models based on problem complexity.',
            'NLP, image processing, predictive ML.',
            ';',
            'code',
            'Integration & Testing',
            'Plug into your existing tools, validate with test cases.',
            'APIs, cron jobs, Slack bots, internal dashboards.',
            ';',
            'repeat',
            'Automation Workflows',
            'Configure logic-based flows to run independently.',
            'Zapier, custom scripts, backend integrations.',
            ';',
            'activity',
            'Monitoring & Optimization',
            'Track model accuracy and automation efficiency.',
            'Retraining loops, failure handling, metrics reporting.'
        ]
    }
                            
]